### ISSUE TITLE
[PAUL-15] Implement disaster recovery

### ISSUE THREAD

**Issue by Serphentas** [kayoumido/HEIGVD-PRO-A-11#15]
This issue tracks the progress for:
- Disaster recovery in cases of total hardware and/or software failure. Basically getting the app to run again from nothing but the source code and a database backup.

Depends on: #5

Estimated duration:
- 4h

Todo:
- *[ ] DR response plan (what to do, in what order (steps), etc.)
- *[ ] Requirements (what to back up, what to assemble to be up and running again, etc.)

**Comment by Lindwing** [comment]
corrected et verified, i close the issue.
