### ISSUE TITLE
[PAUL-5] Setup Docker env

### ISSUE THREAD

**Issue by kayoumido** [kayoumido/HEIGVD-PRO-A-11#5]
Docker environments. These allow both developers and CI/CD pipelines to rapidly deploy and develop/test code.

Estimated duration: 4h
- [x] Definition (what is required by each environment)
- [X] Implementation (creating Docker file(s) per environment)
- [ ]  Testing (ensuring environments work as intended)

Deadline : 22.03.2020

**Comment by Serphentas** [comment]
To put in the first post

---

This issue tracks the progress for:
- Docker environments. These allow both developers and CI/CD pipelines to rapidly deploy and develop/test code.

Estimated duration:
- 4h

- *[ ] Definition (what is required by each environment)
- *[ ] Implementation (creating Docker file(s) per environment)
- *[ ] Testing (ensuring environments work as intended)

**Comment by kayoumido** [comment]
added to issue description

**Comment by kayoumido** [comment]
After looking through the files to solve issues I was having. Some things seems odd and very complicated. So I reverted the changes and recreated the branch
